force-app/main/default/objects/Account/fields/Max_Amount__c.field-meta.xml
<CustomField>
    <fullName>Max_Amount__c</fullName>
    <label>Max Amount</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Amount</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GreatProblem_Test.cls
@isTest
public class GreatProblem_Test {
    @isTest static void GreatProblem_Test() {
        Account acc = new Account(Name = 'Acc', Max_Amount__c = 25);
        insert acc;
        List<Contact> Con = new List<Contact>();
        Contact c = new Contact(LastName = 'Dhairya', Amount__c = 30, AccountId = acc.Id);
        insert c;
        Con.add(c);
        Test.startTest();
        GreatProblem GP = new GreatProblem();
        GP.GreatProblem(Con);
        Test.stopTest();
    }
}