force-app/main/default/objects/Contact/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Amount</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RollUpSummary_test.cls
@isTest
public class RollUpSummary_test {
    @isTest static void RollUpSummary_test() {
        Account acc = new Account(Name = 'Acc', Total_Amount__c = 10);
        insert acc;
        List<Contact> Con = new List<Contact>();
        Contact c = new Contact(LastName = 'Dhairya', Amount__c = 30, AccountId = acc.Id);
        insert c;
        Con.add(c);
        Test.startTest();
        RollUpSummary RUS = new RollUpSummary();
        RUS.RollUpSummary(Con);
        Test.stopTest();
    }
}