force-app/main/default/objects/Api_Key__c/Api_Key__c.object-meta.xml
<CustomObject>
    <label>Api Key Obj</label>
    <nameField>
        <label>Api Key Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Api Key Objs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Api_Key__c/fields/Api_Value__c.field-meta.xml
<CustomField>
    <fullName>Api_Value__c</fullName>
    <label>Api Value</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DpClass_Test.cls
@isTest
public class DpClass_Test {
  @isTest
  public static void ListFiles_Test() {
    Api_Key__c a = new Api_Key__c();
    a.Name = 'First';
    a.Api_Value__c = 'xxxx1ownef';
    insert a;
    Test.setMock(HttpCalloutMock.class, new MockTestHttpClass());
    Test.startTest();
    dPClass.ListFiles();
    String s = dPClass.ListFiles();
    // System.assertEquals('success', s);
    // System.assertEquals('{"example": "test"}', s);
    Test.stopTest();
  }
  @IsTest
  static void DeleteFiles_Test() {
    Api_Key__c a = new Api_Key__c();
    a.Name = 'First';
    a.Api_Value__c = 'xxxx1ownef';
    insert a;
    Test.setMock(HttpCalloutMock.class, new MockTestHttpClass());
    Test.startTest();
    dPClass.DeleteFiles('hello/pdf');
    String s = dPClass.DeleteFiles('hello/pdf');
    // System.assertEquals('success', s);
    // System.assertNotEquals('error', s);
    Test.stopTest();
  }
  @IsTest
  static void UploadFiles_Test(){
    ContentVersion CV = new ContentVersion();
    CV.Title='HelloWorld';
    CV.PathOnClient='HelloWorld.txt';
    CV.VersionData = Blob.valueOf('Hello');
    CV.ContentDocumentId = '0695j00000IESkxAAH';
    insert CV;

    Api_Key__c a = new Api_Key__c();
    a.Name = 'First';
    a.Api_Value__c = 'xxxx1ownef';
    insert a;

    Test.setMock(HttpCalloutMock.class, new MockTestHttpClass());
    Test.startTest();
    dPClass.Upload(CV.ContentDocumentId);
    System.debug(CV.ContentDocumentId);
    String s = dPClass.Upload(CV.ContentDocumentId);
    // System.assertEquals('success', s);
    // System.assertNotEquals('error', s);
    Test.stopTest();
    
  }
}
// }